# Generated by Django 3.2.11 on 2022-01-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email Address', max_length=100)),
                ('full_name', models.CharField(help_text='Full Name', max_length=100)),
            ],
        ),
    ]
